spring:
 profiles:
  active: test
  
logging:
 config: classpath:log4j2-test.xml
 level:
  root: INFO
---
spring:
 profiles: dev
server:
 address: 127.0.0.1
 port: 8080
---
spring:
 profiles: test
server:
 address: 127.0.0.1
 port: 8080
---
spring:
 profiles: prod
server:
 address: 127.0.0.1
 port: 9080